# -*- coding: utf-8 -*-

IS_STATIONARY_AIRCRAFT_RESTORABLE = '2'
NULL = 'null'
WEAPONS_CONTINUATION_MARK = '+'
ROUTE_POINT_EXTRA_PARAMETERS_MARK = 'TRIGGERS'
ROUTE_POINT_RADIO_SILENCE_OFF = '&0'
ROUTE_POINT_RADIO_SILENCE_ON = '&1'
COMMENT_MARKERS = (';', '#', '//', '--', )
